twig:
    default_path: '%kernel.project_dir%/templates'

# Setup image directory
# -> <img src="{{ email.image('@images/img.png') }}">
#paths:
#    '%kernel.project_dir%/public/images': images

when@test:
    twig:
        strict_variables: true
